package zendesk

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"
)

type TicketID uint64

type TicketResponse struct {
	Ticket Ticket `json:"ticket"`
}

type TicketsResponse struct {
	Tickets []Ticket `json:"tickets"`
}
type AutoGenerated struct {
	Ticket Ticket `json:"ticket"`
}

type Ticket struct {
	AssigneeID         uint64                   `json:"assignee_id"`
	BrandID            uint64                   `json:"brand_id"`
	CollaboratorIDs    []uint64                 `json:"collaborator_ids"`
	CreatedAt          time.Time                `json:"created_at"`
	CustomFields       []TicketCustomField      `json:"custom_fields"`
	Description        string                   `json:"description"`
	DueAt              *time.Time               `json:"due_at"`
	EmailCcIds         []uint64                 `json:"email_cc_ids"`
	ExternalID         *string                  `json:"external_id"`
	FollowerIds        []uint64                 `json:"follower_ids"`
	FollowupIds        []uint64                 `json:"followup_ids"`
	GroupID            *uint64                  `json:"group_id"`
	HasIncidents       bool                     `json:"has_incidents"`
	ID                 TicketID                 `json:"id"`
	IsPublic           bool                     `json:"is_public"`
	OrganizationID     *uint64                  `json:"organization_id"`
	Priority           string                   `json:"priority"`
	ProblemID          *uint64                  `json:"problem_id"`
	RequesterID        uint64                   `json:"requester_id"`
	SatisfactionRating TicketSatisfactionRating `json:"satisfaction_rating"`
	Status             string                   `json:"status"`
	Subject            string                   `json:"subject"`
	SubmitterID        uint64                   `json:"submitter_id"`
	Tags               Tags                     `json:"tags"`
	TicketFormID       uint64                   `json:"ticket_form_id"`
	Type               *string                  `json:"type"`
	UpdatedAt          time.Time                `json:"updated_at"`
	URL                string                   `json:"url"`
	Via                TicketVia                `json:"via"`
}

type TicketVia struct {
	Channel string `json:"channel"`
}

type TicketCustomField struct {
	ID    int `json:"id"`
	Value any `json:"value"`
}

type TicketSatisfactionRating struct {
	Score string `json:"score"`
}

// https://developer.zendesk.com/api-reference/ticketing/tickets/tickets/
type TicketService struct {
	client *client
}

// https://developer.zendesk.com/api-reference/ticketing/tickets/tickets/#show-ticket
func (s TicketService) Show(ctx context.Context, id TicketID) (Ticket, error) {
	target := TicketResponse{}

	if err := s.client.jsonRequest(
		ctx,
		http.MethodGet,
		fmt.Sprintf("/api/v2/tickets/%d", id),
		http.NoBody,
		&target,
	); err != nil {
		return Ticket{}, err
	}

	return target.Ticket, nil
}

type TagsPayload struct {
	Tags Tags `json:"tags"`
}

type Tags []string

// https://developer.zendesk.com/api-reference/ticketing/ticket-management/tags/#add-tags
func (s TicketService) AddTags(ctx context.Context, ticketID TicketID, tags Tags) (Tags, error) {
	target := TagsPayload{}

	payloadBuf := new(bytes.Buffer)
	if err := json.NewEncoder(payloadBuf).Encode(TagsPayload{
		Tags: tags,
	}); err != nil {
		return Tags{}, err
	}

	if err := s.client.jsonRequest(
		ctx,
		http.MethodPut,
		fmt.Sprintf("/api/v2/tickets/%d/tags", ticketID),
		payloadBuf,
		&target,
	); err != nil {
		return Tags{}, err
	}

	return target.Tags, nil
}

// https://developer.zendesk.com/api-reference/ticketing/ticket-management/tags/#set-tags
func (s TicketService) SetTags(ctx context.Context, ticketID TicketID, tags Tags) (Tags, error) {
	target := TagsPayload{}

	payloadBuf := new(bytes.Buffer)
	if err := json.NewEncoder(payloadBuf).Encode(TagsPayload{
		Tags: tags,
	}); err != nil {
		return Tags{}, err
	}

	if err := s.client.jsonRequest(
		ctx,
		http.MethodPost,
		fmt.Sprintf("/api/v2/tickets/%d/tags", ticketID),
		payloadBuf,
		&target,
	); err != nil {
		return Tags{}, err
	}

	return target.Tags, nil
}

// https://developer.zendesk.com/api-reference/ticketing/ticket-management/tags/#remove-tags
func (s TicketService) RemoveTags(ctx context.Context, ticketID TicketID, tags Tags) (Tags, error) {
	target := TagsPayload{}

	payloadBuf := new(bytes.Buffer)
	if err := json.NewEncoder(payloadBuf).Encode(TagsPayload{
		Tags: tags,
	}); err != nil {
		return Tags{}, err
	}

	if err := s.client.jsonRequest(
		ctx,
		http.MethodDelete,
		fmt.Sprintf("/api/v2/tickets/%d/tags", ticketID),
		payloadBuf,
		&target,
	); err != nil {
		return Tags{}, err
	}

	return target.Tags, nil
}
